spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  mvc:
    path match:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # ??????? ??? ? ??????? ????? ?? ??? ??
    properties:
      hibernate:
        format_sql: true # ???? query? ???

logging.level:
  org.hibernate.SQL: debug